---
title: "Energy cost minimization"
output: html_document
---

Function `optimize_demand` makes use of Quadratic programming in order to obtain the optimal power load given certain conditions. The Quadratic programming problem can be formulated according to multiple objectives. Currently, flextools package allows to optimize a time-series power load considering two different goals:

* Minimize the power exchanged with the grid (net power)
* Minimize the energy cost

In this article, we'll cover the optimization problem for the first objective: **energy cost minimization**.


# Problem formulation

Our energy cost optimization takes into account multiple profiles of energy prices with the objective to minimize the total cost, considering:

* Imported energy cost
* Exported energy income
* Balancing markets prices (turn up/down demand)
  
The objective function and constraints of this optimization problem are represented below, where:

- $T$ : Number of time intervals within the optimization window
- $G_t$ : Local power generation time-series vector
- $LS_t$ : Non-flexible load time-series vector
- $LF_t$ : Flexible load time-series vector (if not optimized)
- $O_t$ : Optimal flexible load time-series vector
- $I_t$ : imported energy
- $E_t$ : exported energy
- $PI_t$ : imported energy price
- $PE_t$ : exported energy price
- $PTU_t$ : balancing price for turn-up power
- $PTD_t$ : balancing price for turn-down power
- $\lambda$ : penalty on change for the flexible load
- $LFmax$ : Maximum power demand for the flexible load
- $GC_t$ : Grid power capacity time-series vector

Objective function of the optimization problem:

$$
min \sum_{t=1}^{T} I_t·PI_t - E_t·PE_t - PTU_t(O_t-LF_t)  - PTD_t(LF_t-O_t) + \lambda (O_t-LF_t)^{2}
$$


Moreover, this optimization problem has the following constraints:
  
* The energy consumed by the flexible load must remain the same than the expected behavior:

$$
\sum_{t=1}^T O_t \Delta t = \sum_{t=1}^T LF_t \Delta t
$$

* Optimal flexible load must be lower than a certain maximum power:

$$
0 \le O_t \le LFmax_t \quad t \in T
$$

* The energy balance between generation and loads must be lower than the grid capacity:

$$
0 \le O_t \le GC_t + G_t - LS_t \quad t \in T
$$

* The imported energy must remain between 0 and the corresponding energy consumed with the maximum grid capacity:

$$
0 \le I_t \le GC_t \Delta t \quad t \in T
$$

* The exported energy must remain between 0 and power generation:

$$
0 \le E_t \le G_t \Delta t \quad t \in T
$$

* Energy balance behind-the-meter:

$$
I_t - E_t = O_t + LS_t - G_t
$$


At the same time, we can optimize the flexible energy demand with two opposite approaches:

a. Postpone the consumption to later time-slots (**shift the energy forward**)
b. Consume now (store) the energy that will be consumed later (**shift the energy backward**)

We consider both approaches for different objectives or applications. The energy shift is always done within a maximum **time horizon** ($h$) to consider realistic scenarios. For example, the time horizon for the energy demand of a water boiler could have a time horizon of 6 hours, because it wouldn't make sense to heat the water more than 6 hours before the final consumption. Each one of these approaches brings extra constraints to the optimization problem:

If the energy can only be shifted **forward**:

* The cumulative sum of the optimal load $O$ must be higher than the cumulative sum of the original flexible load $LF$ except the last $h$ time slots, and lower than the total cumulative sum of the original flexible load $LF$ (energy can only be shifted forwards):
    
$$
\sum_{t = 1}^{u-h} LF_t \le \sum_{t=1}^u O_t \le \sum_{t=1}^u LF_t \quad u = 1 \dots T
$$

* The maximum values for the optimal demand $O_t$ will depend on the time horizon $h$:

$$
O_u \le \sum_{t = u-h}^u LF_t \quad u = 1 \dots T
$$


If the energy can only be shifted **backward**:

* The cumulative sum of the optimal demand $O$ must be higher than the total cumulative sum of the original demand $LF$ (energy can only be shifted backwards), and lower than the cumulative sum of the original demand $LF$ except the following $h$ time slots:
    
$$
\sum_{t=1}^u LF_t \le \sum_{t=1}^u O_t \le \sum_{t=1}^{u+h} LF_t \quad u = 1 \dots T
$$

* The maximum values for the optimal demand $O_t$ will depend on the time horizon $h$:

$$
O_u \le \sum_{t = u}^{u+h} LF_t \quad u = 1 \dots T
$$


# Quadratic programming
  
Considering that the objective function of this problem has quadratic terms, a Quadratic Programming algorithm must be used. In this case we have used the R package `osqp`, visit their [website](https://osqp.org/) for more information.

The form of a [quadratic problem](https://osqp.org/docs/solver/index.html) is:

$$
  \begin{array}{ll} 
  \text{minimize} & \mathrm (1/2) x^\top \mathrm P \, \mathrm x + \mathrm q^{\top} \mathrm x \\ 
  \text{subject to} & \mathrm l \leq \mathrm Ax \leq \mathrm u
  \end{array}
$$

The OSQP function `osqp::solve_osqp(P, q, A, l, u)` requires the parameters `P`, `q`, `A`, `l` and `u`. These parameters must be extracted from our problem formulation, so developing the objective function we can create `P` and `q` and from constraints we can create `A`, `l` and `u`.

Then:

$$
P = 2 · \mathbb{I} · \lambda
$$
$$
q = PTD - PTU - 2·\lambda·LF + PI - PE
$$



